In [69]:
print("Hello")

Hello

In [70]:
import pandas as pd

df = pd.read_csv("../data/US_Accidents_March23.csv")

print("Dataset Loaded Successfully")
print("Shape:", df.shape)

Dataset Loaded Successfully
Shape: (7728394, 46)

In [71]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [72]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     str
 1   Source                 str
 2   Severity               int64
 3   Start_Time             str
 4   End_Time               str
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            str
 11  Street                 str
 12  City                   str
 13  County                 str
 14  State                  str
 15  Zipcode                str
 16  Country                str
 17  Timezone               str
 18  Airport_Code           str
 19  Weather_Timestamp      str
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         str
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      str
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         str
 43  Civil_Twilight         str
 44  Nautical_Twilight      str
 45  Astronomical_Twilight  str
dtypes: bool(13), float64(12), int64(1), str(20)
memory usage: 3.6 GB

In [74]:
df.columns.tolist()

['ID',
 'Source',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'Description',
 'Street',
 'City',
 'County',
 'State',
 'Zipcode',
 'Country',
 'Timezone',
 'Airport_Code',
 'Weather_Timestamp',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

In [75]:
df.isnull().sum().sort_values(ascending=False)

End_Lng                  3402762
End_Lat                  3402762
Precipitation(in)        2203586
Wind_Chill(F)            1999019
Wind_Speed(mph)           571233
Visibility(mi)            177098
Wind_Direction            175206
Humidity(%)               174144
Weather_Condition         173459
Temperature(F)            163853
Pressure(in)              140679
Weather_Timestamp         120228
Sunrise_Sunset             23246
Civil_Twilight             23246
Astronomical_Twilight      23246
Nautical_Twilight          23246
Airport_Code               22635
Street                     10869
Timezone                    7808
Zipcode                     1915
City                         253
Description                    5
ID                             0
Distance(mi)                   0
Start_Lng                      0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
County                         0
Amenity                        0
Country                        0
State                          0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
Station                        0
Roundabout                     0
Railway                        0
No_Exit                        0
Turning_Loop                   0
Traffic_Signal                 0
Traffic_Calming                0
Stop                           0
dtype: int64

In [76]:
selected_cols = [
    'Severity',
    'Start_Time',
    'Start_Lat',
    'Start_Lng',
    'Temperature(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Speed(mph)',
    'Weather_Condition'
]

df = df[selected_cols]

In [77]:
df = df[selected_cols]

In [78]:
df.isnull().sum()

Severity                  0
Start_Time                0
Start_Lat                 0
Start_Lng                 0
Temperature(F)       163853
Humidity(%)          174144
Pressure(in)         140679
Visibility(mi)       177098
Wind_Speed(mph)      571233
Weather_Condition    173459
dtype: int64

In [79]:
num_cols = [
    'Temperature(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Speed(mph)'
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [80]:
df['Weather_Condition'] = df['Weather_Condition'].fillna('Unknown')

In [81]:
df['Weather_Condition'] = df['Weather_Condition'].fillna('Unknown')

In [82]:
print(df.isnull().sum())

Severity             0
Start_Time           0
Start_Lat            0
Start_Lng            0
Temperature(F)       0
Humidity(%)          0
Pressure(in)         0
Visibility(mi)       0
Wind_Speed(mph)      0
Weather_Condition    0
dtype: int64

In [83]:
df['Start_Time'] = pd.to_datetime(
    df['Start_Time'],
    format='mixed'
)

df['Hour'] = df['Start_Time'].dt.hour
df['Month'] = df['Start_Time'].dt.month
df['DayOfWeek'] = df['Start_Time'].dt.dayofweek

df.drop('Start_Time', axis=1, inplace=True)

df.head()

,Severity,Start_Lat,Start_Lng,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Weather_Condition,Hour,Month,DayOfWeek
0,3,39.865147,-84.058723,36.9,91.0,29.68,10.0,7.0,Light Rain,5,2,0
1,2,39.928059,-82.831184,37.9,100.0,29.65,10.0,7.0,Light Rain,6,2,0
2,2,39.063148,-84.032608,36.0,100.0,29.67,10.0,3.5,Overcast,6,2,0
3,3,39.747753,-84.205582,35.1,96.0,29.64,9.0,4.6,Mostly Cloudy,7,2,0
4,2,39.627781,-84.188354,36.0,89.0,29.65,6.0,3.5,Mostly Cloudy,7,2,0

In [84]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Weather_Condition'] = le.fit_transform(
    df['Weather_Condition']
)

df.head()

,Severity,Start_Lat,Start_Lng,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Weather_Condition,Hour,Month,DayOfWeek
0,3,39.865147,-84.058723,36.9,91.0,29.68,10.0,7.0,62,5,2,0
1,2,39.928059,-82.831184,37.9,100.0,29.65,10.0,7.0,62,6,2,0
2,2,39.063148,-84.032608,36.0,100.0,29.67,10.0,3.5,88,6,2,0
3,3,39.747753,-84.205582,35.1,96.0,29.64,9.0,4.6,85,7,2,0
4,2,39.627781,-84.188354,36.0,89.0,29.65,6.0,3.5,85,7,2,0

In [85]:
df['Risk'] = (df['Severity'] >= 3).astype(int)

df.drop('Severity', axis=1, inplace=True)

df.head()

,Start_Lat,Start_Lng,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Weather_Condition,Hour,Month,DayOfWeek,Risk
0,39.865147,-84.058723,36.9,91.0,29.68,10.0,7.0,62,5,2,0,1
1,39.928059,-82.831184,37.9,100.0,29.65,10.0,7.0,62,6,2,0,0
2,39.063148,-84.032608,36.0,100.0,29.67,10.0,3.5,88,6,2,0,0
3,39.747753,-84.205582,35.1,96.0,29.64,9.0,4.6,85,7,2,0,1
4,39.627781,-84.188354,36.0,89.0,29.65,6.0,3.5,85,7,2,0,0

In [86]:
print(df['Risk'].value_counts())

Risk
0    6224347
1    1504047
Name: count, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split

X = df.drop('Risk', axis=1)
y = df['Risk']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (6182715, 11)
Testing Shape: (1545679, 11)

In [88]:
df_sample = df.sample(
    n=100000,
    random_state=42
)

print(df_sample.shape)

(100000, 12)

In [89]:
X = df_sample.drop('Risk', axis=1)
y = df_sample['Risk']

In [90]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [51]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=20,
    max_depth=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [91]:
import joblib

joblib.dump(model, "../models/risk_model.pkl")

['../models/risk_model.pkl']

In [52]:

print("Training Complete")

Training Complete

In [53]:
pred = model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.65      0.75     16087
           1       0.32      0.67      0.43      3913

    accuracy                           0.65     20000
   macro avg       0.60      0.66      0.59     20000
weighted avg       0.78      0.65      0.69     20000

In [54]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.6505

In [55]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.65      0.75     16087
           1       0.32      0.67      0.43      3913

    accuracy                           0.65     20000
   macro avg       0.60      0.66      0.59     20000
weighted avg       0.78      0.65      0.69     20000

In [56]:
import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

              Feature  Importance
7   Weather_Condition    0.211634
1           Start_Lng    0.206722
0           Start_Lat    0.203045
4        Pressure(in)    0.094399
6     Wind_Speed(mph)    0.090091
2      Temperature(F)    0.046427
3         Humidity(%)    0.039814
9               Month    0.039174
8                Hour    0.030753
10          DayOfWeek    0.023839
5      Visibility(mi)    0.014102

In [57]:
import joblib

joblib.dump(
    model,
    "../models/risk_model.pkl"
)

print("Model Saved Successfully")

Model Saved Successfully

In [58]:
joblib.dump(
    le,
    "../models/weather_encoder.pkl"
)

print("Encoder Saved")

Encoder Saved

In [59]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.6505

In [60]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.65      0.75     16087
           1       0.32      0.67      0.43      3913

    accuracy                           0.65     20000
   macro avg       0.60      0.66      0.59     20000
weighted avg       0.78      0.65      0.69     20000

In [61]:
import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

              Feature  Importance
7   Weather_Condition    0.211634
1           Start_Lng    0.206722
0           Start_Lat    0.203045
4        Pressure(in)    0.094399
6     Wind_Speed(mph)    0.090091
2      Temperature(F)    0.046427
3         Humidity(%)    0.039814
9               Month    0.039174
8                Hour    0.030753
10          DayOfWeek    0.023839
5      Visibility(mi)    0.014102

In [62]:
import os

print(os.listdir("../models"))

['risk_model.pkl', 'weather_encoder.pkl']

In [63]:
import joblib

encoder = joblib.load("../models/weather_encoder.pkl")

for i, condition in enumerate(encoder.classes_):
    print(i, condition)

0 Blowing Dust
1 Blowing Dust / Windy
2 Blowing Sand
3 Blowing Snow
4 Blowing Snow / Windy
5 Blowing Snow Nearby
6 Clear
7 Cloudy
8 Cloudy / Windy
9 Drifting Snow
10 Drifting Snow / Windy
11 Drizzle
12 Drizzle / Windy
13 Drizzle and Fog
14 Dust Whirls
15 Duststorm
16 Fair
17 Fair / Windy
18 Fog
19 Fog / Windy
20 Freezing Drizzle
21 Freezing Rain
22 Freezing Rain / Windy
23 Funnel Cloud
24 Hail
25 Haze
26 Haze / Windy
27 Heavy Blowing Snow
28 Heavy Drizzle
29 Heavy Freezing Drizzle
30 Heavy Freezing Rain
31 Heavy Freezing Rain / Windy
32 Heavy Ice Pellets
33 Heavy Rain
34 Heavy Rain / Windy
35 Heavy Rain Shower
36 Heavy Rain Shower / Windy
37 Heavy Rain Showers
38 Heavy Sleet
39 Heavy Sleet / Windy
40 Heavy Sleet and Thunder
41 Heavy Smoke
42 Heavy Snow
43 Heavy Snow / Windy
44 Heavy Snow with Thunder
45 Heavy T-Storm
46 Heavy T-Storm / Windy
47 Heavy Thunderstorms and Rain
48 Heavy Thunderstorms and Snow
49 Heavy Thunderstorms with Small Hail
50 Ice Pellets
51 Light Blowing Snow
52 Light Drizzle
53 Light Drizzle / Windy
54 Light Fog
55 Light Freezing Drizzle
56 Light Freezing Fog
57 Light Freezing Rain
58 Light Freezing Rain / Windy
59 Light Hail
60 Light Haze
61 Light Ice Pellets
62 Light Rain
63 Light Rain / Windy
64 Light Rain Shower
65 Light Rain Shower / Windy
66 Light Rain Showers
67 Light Rain with Thunder
68 Light Sleet
69 Light Sleet / Windy
70 Light Snow
71 Light Snow / Windy
72 Light Snow Grains
73 Light Snow Shower
74 Light Snow Shower / Windy
75 Light Snow Showers
76 Light Snow and Sleet
77 Light Snow and Sleet / Windy
78 Light Snow with Thunder
79 Light Thunderstorm
80 Light Thunderstorms and Rain
81 Light Thunderstorms and Snow
82 Low Drifting Snow
83 Mist
84 Mist / Windy
85 Mostly Cloudy
86 Mostly Cloudy / Windy
87 N/A Precipitation
88 Overcast
89 Partial Fog
90 Partial Fog / Windy
91 Partly Cloudy
92 Partly Cloudy / Windy
93 Patches of Fog
94 Patches of Fog / Windy
95 Rain
96 Rain / Windy
97 Rain Shower
98 Rain Shower / Windy
99 Rain Showers
100 Rain and Sleet
101 Sand
102 Sand / Dust Whirls Nearby
103 Sand / Dust Whirlwinds
104 Sand / Dust Whirlwinds / Windy
105 Sand / Windy
106 Scattered Clouds
107 Shallow Fog
108 Shallow Fog / Windy
109 Showers in the Vicinity
110 Sleet
111 Sleet / Windy
112 Sleet and Thunder
113 Small Hail
114 Smoke
115 Smoke / Windy
116 Snow
117 Snow / Windy
118 Snow Grains
119 Snow Showers
120 Snow and Sleet
121 Snow and Sleet / Windy
122 Snow and Thunder
123 Snow and Thunder / Windy
124 Squalls
125 Squalls / Windy
126 T-Storm
127 T-Storm / Windy
128 Thunder
129 Thunder / Windy
130 Thunder / Wintry Mix
131 Thunder / Wintry Mix / Windy
132 Thunder and Hail
133 Thunder and Hail / Windy
134 Thunder in the Vicinity
135 Thunderstorm
136 Thunderstorms and Rain
137 Thunderstorms and Snow
138 Tornado
139 Unknown
140 Volcanic Ash
141 Widespread Dust
142 Widespread Dust / Windy
143 Wintry Mix
144 Wintry Mix / Windy

In [64]:
df.head()

,Start_Lat,Start_Lng,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Weather_Condition,Hour,Month,DayOfWeek,Risk
0,39.865147,-84.058723,36.9,91.0,29.68,10.0,7.0,62,5,2,0,1
1,39.928059,-82.831184,37.9,100.0,29.65,10.0,7.0,62,6,2,0,0
2,39.063148,-84.032608,36.0,100.0,29.67,10.0,3.5,88,6,2,0,0
3,39.747753,-84.205582,35.1,96.0,29.64,9.0,4.6,85,7,2,0,1
4,39.627781,-84.188354,36.0,89.0,29.65,6.0,3.5,85,7,2,0,0

In [65]:
print(df.columns.tolist())

['Start_Lat', 'Start_Lng', 'Temperature(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Speed(mph)', 'Weather_Condition', 'Hour', 'Month', 'DayOfWeek', 'Risk']

In [66]:
df['Risk'].value_counts()

Risk
0    6224347
1    1504047
Name: count, dtype: int64

In [67]:
pred = model.predict(X_test)

import pandas as pd

print(pd.Series(pred).value_counts())

0    11659
1     8341
Name: count, dtype: int64

In [68]:
import joblib

joblib.dump(model, "../models/risk_model.pkl")

print("New Model Saved")

New Model Saved

In [94]:
import joblib

joblib.dump(model, "../models/risk_model.pkl")

['../models/risk_model.pkl']